### ISSUE TITLE
Принципы построения синхронного API: GET статус 204 vs 404 vs 200; пагинация

### ISSUE THREAD

**Issue by sergey-volkov-lm** [adeo/lmru--tech#18]
> ### 204 или 404
> Есть небольшой спор: какой код возвращать в случае когда URL корректный, но информация не найдена? Мы рекоммендуем возвращать 404 в случае когда информация запрашивалась по ключу, и 204 когда информация была не найдена после фильтрации или поиска по параметрам.

1. Если мы говорим о единственно возможной сущности в ответе, то рекомендуется возвращать пустое тело ответа вместе с 204 статусом? Потому что по http-спецификации с таким статусом не должно быть тела ответа.
2. Если мы говорим о запросе на получение 0..n сущностей в списке, с пагинацией или без, 204 кажется совсем неправильной опцией.
Лучше возвращать 200 с телом `[]` или
```
{
  "totalPages": 0,
  "totalCount": 0,
  "pageSize": 0,
  "pageIndex": 0,
  "content": []
}
```

> ### Пагинация по номеру страницы.
> `?page=2&perPage=100`

page с какой цифры начинается? С 0 или с 1? Было бы понятнее, кмк, использовать pageIndex (принято, что индексы с нуля) и pageSize понятия соответственно.

**Comment by 60032270** [comment]
1. 404 у нас возвращается, когда мы обращаемся к конкретному ресурсу: /customers/{id}  это нормально, что возвращается ошибка, так как такого ресурса с данным {id} не существует. в случае когда мы используем query parameters для получения результата, мы не обращаемся к конкретному ресурсы, мы обращаемся к коллекции с указанными параметрами и логично возвращать не ошибку. 2. 204 при обращение к коллекции с использованием query parameters не требует парсинга body, а позволяет сразу обработать эту ситуацию по коду ответа. В примере который указа выше, нужно будет парсить body

**Comment by sergey-volkov-lm** [comment]
Т.е. рекомендуется потребителям апи ориентироваться на статус код ответа, а не на содержание body? Как пришли к этому? Насколько это жёсткое требование?

**Comment by groundsfar** [comment]
1. >Мы рекоммендуем возвращать 404 в случае когда информация запрашивалась по ключу
Тоже странная практика. Но я такое наблюдал при интеграции с Microsoft продуктами. Тоже вызывает кучу вопросов и как до этого вообще дошли, буду чекать issue этот.
2. Лично яб делал с единицы будь то потребитель фронт или бэк, т.к ты не позицию передаешь

**Comment by 60032270** [comment]
Т.е. рекомендуется потребителям апи ориентироваться на статус код ответа, а не на содержание body? Как пришли к этому? Насколько это жёсткое требование? _Код ответа должен соответствовать ответу от бека (код 200 для всех случаев ошибок с описанием в боди ошибки, это запрещено), при публикации каноников это проверяется . Жестких правил ориентироваться на код ответа нет, но в каких то случаях буде проще ориентироваться на него, если все будут соблюдать правила по использованию кодов ответа описанных гайде_ 
Не может быть такого, например, что фронту легче встроить массив из json'а в UI как есть (если пустой, то ок), а не делать проверки? _Ну если только ответ будет читабельным, что бывает не всегда. Как вариант еще, если возвращается ответ без тела, как 204, можно выводить описание кода NOT FOUND_

**Comment by 60032270** [comment]
Тоже странная практика. Но я такое наблюдал при интеграции с Microsoft продуктами. Тоже вызывает кучу вопросов и как до этого вообще дошли, буду чекать issue этот.
2. Лично яб делал с единицы будь то потребитель фронт или бэк, т.к ты не позицию передаешь а индентификатор.
_404 в таком ключе использует google, amazon, visa:
amazon
404	Error	HTTP Status Code 404: Resource not found due to incorrect input. Correct your request and then retry it.

google
404	NOT_FOUND	A specified resource is not found, or the request is rejected by undisclosed reasons, such as whitelisting.

visa
404	NOT FOUND	The project is trying to hit an endpoint that does not exist.Refer to the API documentation to validate you are hitting the right endpoint. 
_

**Comment by voborgus** [comment]
Закрываю как неактивную, при необходимости — переоткройте.
