### ISSUE TITLE
Архитектура: Клиентские библиотеки

### ISSUE THREAD

**Issue by vitaliyzzz42** [adeo/lmru--tech#26]
> Сервисы не должны предоставлять клиентскую библиотеку. API и модель данных выражается через REST и JSON

Например, есть библиотека Opus, которую многие используют (хоть и разработана она изначально командой Solution). Было бы нецелесообразно разрабатывать её каждой команде с нуля по спецификации API.

Многие крупные сервисы предоставляют официальные библиотеки (SDK) для ускорения разработки:
https://developers.google.com/api-client-library
https://webservices.amazon.com/paapi5/documentation/quick-start/using-sdk.html

Предлагаю изменить формулировку на

> REST API и JSON модель данных первичны. Сервис должен предоставлять документацию по ним потребителям, и именно она определяет контракт сервиса, независимо от наличия клиентской библиотеки

**Comment by sergey-volkov-lm** [comment]
Может просто убрать упоминание клиентской библиотеки?

**Comment by vch-lm** [comment]
Я переживаю, что в не очень зрелых командах могут возникнуть проблемы с поддержкой обоих вещей в актуальном состоянии - либо библиотека, либо спека будут отставать (сейчас не все команды имеют даже спеку в актуальном состоянии).  Команды напрямую не заинтересованы в поддержке библиотек для своего апи, у нас не только java - на все языки библиотеки не сделаешь. Если бы библиотеки автогенерировались из сваггера и были интегрированы в какой-нибудь dev-портал, было бы прикольно, но руками это все содержать - сомнительно.

**Comment by VlasyukA** [comment]
Библиотека opus, не предоставляется командой opus. Не вижу тут противоречия

**Comment by voborgus** [comment]
> Библиотека opus не предоставляется командой opus. Не вижу тут противоречия

@VlasyukA тем более, хорошо ещё когда она внутри одного домена (когда ты сам сделал её для своего удобства и заинтересован в её поддержке), а тут даже не понятно к кому бежать в случае необходимости.

**Comment by yrsh** [comment]
Это всё очень сильно походе на путаницу, не надо мешать сервисы и библиотеки в одну кучу. Если есть межпроцессное взаимодействие микросервисы и всякий IPC, при котором задействуются сетевые протоколы и энкодинг сообщений, то уже никакая не библиотека, а сервис.
Значит и рассматривать это надо как микросервис. Формулировку про REST и JSON лучше вообще убрать. REST - топорная и не гибкая модель, не подходит ни для чего кроме простых CRUD'ов. Аналогично и JSON - формат годный только для небольших текстовых данных и то, далеко не всех.
Простой пример, сервис для работы с любым брокером сообщений потребует асинхронного протокола, например ws вместо того же http (можно взять и http конечно если хочется костылей о оверхеда) и формата данных с поддержкой бинарных форматов для передачи сырых буферов.

Для сервиса лучше сократить до

> API должно иметь детальное описание в одном из общепринятых форматов: **Swagger**, **AsyncAPI**, **GRPC API definition**.

И на этом всё - остальное будет по большей части лишь ограничениями.


API библиотек вообще никому нечем не обязан, библиотека она то и библиотека, что работает только внутри целевого рантайма или экосиситемы, в которой вообще не предусматривается никаких контрактов и ограничений кроме синтаксиса самого языка и его стандартных объектов. Например библиотека для Go может выставлять потоки событий как экземпляры Channel, а NodeJS как Stream, итд.

**Comment by voborgus** [comment]
```
библиотека она то и библиотека, что работает только внутри целевого рантайма или экосиситемы
```
Всё так, здесь как раз в качестве примера была приведена достаточно популярная Java библиотека, и она шарится между доменами и поддерживается одним из них (не авторами сервиса).

```
Swagger, AsyncAPI, GRPC API definition.
```
GRPC на сегодня не является разрешённым способом синхронной интеграции между доменами, поэтому пока только обычный HTTP(S) и текстовый небинарный JSON.

Предлагаю вынести на обсуждение в [тех. комитет](https://tech.leroymerlin.ru/stack/committee/) и договориться:

* Можно ли синхронное бинарное междоменное взаимодействие
* Можно ли в GRPC меж доменами ходить
* Уточнить формулировку по асинхронному взаимодействию и рекомендованным подходам
* Можно ли шарить библиотеки между доменами или предоставлять потреблять другим доменам свой сервис через библиотеку

@alem355 призываю тебя в этот топик :)

**Comment by yrsh** [comment]
Не совсем, между доменами же может быть кафка, а значит есть асинхронная модель взаимодействия и бинарный формат (Avro).

**Comment by voborgus** [comment]
Вынес вопрос на собрание следующего тех. комитета 17 декабря.

**Comment by voborgus** [comment]
По первым трём вопросам договорились:
перефразировать в ценностях текст во что-то со смыслом 
`протокол взаимодействия определяется согласно принятому стеку технологий` со ссылкой на [стек](https://tech.leroymerlin.ru/stack/),
а в стек добавить новую строку `междоменное взаимодействие`, где разложить технологии по категориям.

Последний вопрос отложили до следующего раза.

@alem355 @jbuckwheat  FYI

**Comment by voborgus** [comment]
Договорились:

> Предоставление библиотеки SDK к своим API наружу продукта — дополнительная и не обязательная возможность. Эта библиотека должна быть доступна для входящих контрибьюций по InnerSource. Ответственность в поддержании консистентности библиотеки с фактическим контрактом, её своевременным обновлением и полнотой документации — за командой представляющей API. Это относится к библиотекам на всех языках, которые она приняла к себе на поддержку. Команда может не принять на поддержку библиотеку, написанную третьими лицами, но в таком случае эта библиотека не должна обмениваться между продуктами. Команда может выводить из эксплуатации библиотеки только при покидании последнего его потребителя. Внутри продукта можно использовать свои библиотечки как угодно.

Попробую перефразировать это в ещё один архитектурный принцип.

**Comment by voborgus** [comment]
В стеке появились две новые строчки — межпродуктовое и внутрипродуктовое взаимодействие.

https://tech.leroymerlin.ru/stack/

**Comment by voborgus** [comment]
По второму PR движения не было, если будет кому-то актуально, переоткрывайте.
