### ISSUE TITLE
Добавить CODEOWNERS, ISSUE_TEMPLATE, PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by alinkov** [adeo/lmru--tech#31]
Необходимо добавить следующие файлы в репозиторий для улучшения опыта ревью:
 - [ISSUE_TEMPLATE](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)
 - [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)
 - [PULL_REQUEST_TEMPLATE](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

Аналогичное задача в другой репозиторий https://github.com/adeo/lmru--devops--pipeline-shared-library/issues/113

**Comment by voborgus** [comment]
Не актуально в силу небольшого количество issues и PR к ревью.
