### ISSUE TITLE
Async API: reconsider kafka topic naming conventions

### ISSUE THREAD

**Issue by sergey-volkov-lm** [adeo/lmru--tech#50]
https://tech.leroymerlin.ru/knowledge/async/

Допустим, для приложения solution repository и объекта solution task, при публикации объектов в кафку, рекомендуется название топика
`solutionRepository-canonical-int-orders-solutionTask-v1`
В то же время, общераспространённые рекомендации по неймингу топиков в кафке выступают против использования больших букв. Пример https://devshawn.com/blog/apache-kafka-topic-naming-conventions/

По информации от dba специалистов и Владимира Андреева, топик должен выглядеть следующим образом
`solution-repository-canonical-int-orders-solution-task-v1`

На мой взгляд и взгляд автора статьи, идеально было бы
`solution-repository.canonical.int.orders.solution-task.v1`
Но dba не готовы к точкам из-за конфликтов . и _ в кафке.

Прошу привести рекомендации в актуальное состояние.

Возможно, актуально и для названий rabbitmq exchange.

**Comment by voborgus** [comment]
Смотрю, изучаю, поправлю. Спасибо!

**Comment by panovst** [comment]
а вы не смотрели на [конвенцию наименования](https://github.com/adeo/adeo-data-streaming-platform/blob/master/docs/Governance/1-Kafka-Topics-Naming-Convention.md#convention) в Adeo?

**Comment by voborgus** [comment]
> а вы не смотрели на [конвенцию наименования](https://github.com/adeo/adeo-data-streaming-platform/blob/master/docs/Governance/1-Kafka-Topics-Naming-Convention.md#convention) в Adeo?

Привет! Команда интеграции на постоянном контакте с сообществом адео
