### ISSUE TITLE
Нет возможности ссылаться на блоки

### ISSUE THREAD

**Issue by OlgaReshatneva** [adeo/lmru--tech#70]
Например: Нет возможности ссылаться на блок "Соглашение о названиях" на странице [Принципы построения асинхронного API](https://tech.leroymerlin.ru/knowledge/async/)

**Comment by voborgus** [comment]
При наведении на заголовок появляется значок ссылки с [указателем на конкретный блок](https://tech.leroymerlin.ru/knowledge/async/#%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D1%85), но вероятно это можно сделать лучше, добавив при клике адрес в адресную строку и заменить кириллицу на латинские символы (это можно сделать стандартными способами генератора этого сайта -- hugo.
