### ISSUE TITLE
Использование более совершенного инструмента для UI end-to-end тестов

### ISSUE THREAD

**Issue by darkallure** [adeo/lmru--tech#73]
Использовать Playwright для написания UI end-to-end тестов: https://playwright.dev/

Пробема: На данный момент используется фреймворк(wrapper Selenium) Selenide, который значительно уступает по функционалу/возможностям автоматизации интерфейса, а также по скорости выполнения тестов. Playwright основан на всем известном Puppeteer, что делает его самым быстрым среди подобного рода фреймворков, так как скрипты запускаются непосредственно в самом браузере, а не через WebDriver как в случае с Selenide.

**Comment by darkallure** [comment]
https://playwright.dev/

**Comment by Mystery-xx** [comment]
Сейчас идет пилотирование Playwright. По результатам пилота будет принято решение о дальнейшем его использовании.

**Comment by voborgus** [comment]
https://leroymerlin-tech.ru/stack/table/ – Playwright появился в обновлённой таблице технологий.
