### ISSUE TITLE
Тут с разделами ошибочка вышла

### ISSUE THREAD

**Issue by anyapoliakova** [adeo/lmru--tech#80]
Привет! 
У вас вроде как сначала подраздел "Практики и ритуалы", а потом "Антипаттерн". Но кто-то что-то напутал и оно перемешалось на этой странице:
https://leroymerlin-tech.ru/values/architecture/
Пожалуйста, сделайте, чтобы было красиво, как на всех других.

**Comment by voborgus** [comment]
И правда, спасибо большое!
