### ISSUE TITLE
Разработка backend на Python и FastAPI

### ISSUE THREAD

**Issue by 61803** [adeo/lmru--tech#86]
1. Нужно добавить раздел, соответствующий Business applications - backend (сейчас есть только CRUD).
2. Добавить Python в качестве инструмента для разработки Business applications - backend.
3. Добавить FastAPI в качестве инструмента для CRUD.
4. Давно есть успешно работающие сервисы, использующие эти инструменты.

**Comment by alem355** [comment]
Привет! Скорей всего у нас есть разночтение в понимании Business applications - backend. Насколько я знаю, в вашем домене в основном дата продукты, в этом случае с Python  никаких проблем нет.

Давай встретимся и обсудим.
